#!/bin/bash
#Recursive DoFile Replacer
TMP=$(cat $1);
for MATCH in $(sed -n 's/dofile(getSystemMacroValue("$SCENARIO_PATH").."\([[:alnum:]\/\.]*\)")/\1/p' $1)
do
	LINE=$(echo "$TMP" | grep -n ".*dofile(getSystemMacroValue(\"\$SCENARIO_PATH\")..\"$MATCH\")" | cut -f1 -d:);
	INDENT=$(echo "$TMP" | sed -n "${LINE}p" | sed "s;^\([[:space:]]*\)dofile(getSystemMacroValue(\"\$SCENARIO_PATH\")..\"$MATCH\");\1;");
	TMP=$(echo "$TMP" | head -n $(($LINE-1));echo "$($0 $MATCH)" | sed "s/^/$INDENT/"; echo "$TMP" | tail -n +$(($LINE+1)) );
done
echo "$TMP";
