#!/bin/bash
#Recursive Included Files Finder
for MATCH in $(sed -n 's/.*require "\([[:alnum:]\.]*\)"/\1/p' $1)
do
	FILENAME=$(echo "$MATCH" | sed "s/\./\//g").lua;
	echo $FILENAME;
	$0 $FILENAME;
done
